export const seedDiagnoses = [
  {
    id: '1',
    animal_type: 'cattle',
    symptoms_text: 'Blisters on mouth',
    disease: 'Foot and Mouth Disease',
    confidence: 89,
    severity: 'high',
    vet_required: true,
    zoonotic_risk: false,
    lat: 27.7172,
    lng: 85.3240,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&q=80&w=400',
    description: 'A highly contagious viral disease affecting cattle and swine.',
    immediate_action: 'Isolate the animal immediately. Do not move off farm.',
    treatment: '1. Call a vet. 2. Provide soft feed. 3. Treat secondary infections.',
    prevention: 'Vaccinate healthy animals and strictly control movement.',
  },
  {
    id: '2',
    animal_type: 'poultry',
    symptoms_text: 'Sudden death, twisted neck',
    disease: 'Newcastle Disease',
    confidence: 92,
    severity: 'critical',
    vet_required: true,
    zoonotic_risk: false,
    lat: 27.4712,
    lng: 89.6395,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&q=80&w=400',
    description: 'An acute respiratory and neurological disease of birds.',
    immediate_action: 'Cull affected birds and isolate the flock.',
    treatment: 'No specific treatment. Antibiotics may prevent secondary infections.',
    prevention: 'Routine vaccination is the only effective prevention.',
  },
  {
    id: '3',
    animal_type: 'cattle',
    symptoms_text: 'High fever, skin lesions',
    disease: 'Foot and Mouth Disease',
    confidence: 78,
    severity: 'high',
    vet_required: true,
    zoonotic_risk: false,
    lat: 27.5030,
    lng: 84.3542,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&q=80&w=400',
    description: 'A highly contagious viral disease affecting cattle and swine.',
    immediate_action: 'Isolate the animal immediately. Do not move off farm.',
    treatment: '1. Call a vet. 2. Provide soft feed. 3. Treat secondary infections.',
    prevention: 'Vaccinate healthy animals and strictly control movement.',
  },
  {
    id: '4',
    animal_type: 'goat',
    symptoms_text: 'Mouth ulcers, nasal discharge',
    disease: 'PPR',
    confidence: 85,
    severity: 'critical',
    vet_required: true,
    zoonotic_risk: false,
    lat: 23.8103,
    lng: 90.4125,
    created_at: new Date(Date.now() - 500000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&q=80&w=400',
    description: 'Peste des Petits Ruminants, severe viral disease of goats/sheep.',
    immediate_action: 'Isolate affected animals instantly.',
    treatment: 'Supportive care. Antibiotics for secondary infections.',
    prevention: 'Vaccination of flock is highly effective.',
  },
];

export const seedOutbreaks = [
  {
    disease: 'Foot and Mouth Disease',
    count: 2,
    region: 'Chitwan District',
    severity: 'high',
    lat: 27.6101,
    lng: 84.8391
  }
];
