services:
  mongodb:
    image: mongo:7
    container_name: maternal-risk-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: maternal-risk-ai
    restart: unless-stopped
    ports:
      - '8000:8000'

volumes:
  mongo_data:
